name: Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - image: 22.04
          suffix:
        - image: 18.04
          suffix: -18.04
          # Some older clangs (<10) needs to be an older glibc, as comes with 18.04 in order to build 9.* and earlier.
          # otherwise we somehow need to apply 947f9692440836dcb8d88b74b69dd379d85974ce to get the sanitizer
          # to build.
        - image: 16.04
          suffix: -16.4
          # Ancient Clang builds (2.6-4.0) assume 16.04 environment. 
    steps:
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push to Docker Hub
      id: hub_build
      uses: docker/build-push-action@v6
      with:
        push: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
        tags: compilerexplorer/clang${{ matrix.suffix }}-builder:latest
        cache-from: type=registry,ref=compilerexplorer/clang${{ matrix.suffix }}-builder:latest
        cache-to: type=inline,mode=max
        file: Dockerfile
        build-args: image=${{ matrix.image }}
    - name: Docker Hub Image Digest
      run: echo ${{ steps.hub_build.outputs.digest }}
